; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
; 
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; 


[env:esp32dev]
;platform = espressif32@3.5.0
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
   ;Gerenciamento de Tarefas
   ;makuna/Task @ 1.1.6  
   ;crankyoldgit/IRremoteESP8266@^2.7.11 -> Nao funciona
   adafruit/Adafruit Unified Sensor @^1.1.4
   adafruit/DHT sensor library@^1.4.3
   
   openenergymonitor/EmonLib @ 1.1.0
   ;Protocolos e Comunicação
   bblanchon/ArduinoJson @ 6.19.4
   knolleary/PubSubClient @ 2.8.0
   arduino-libraries/NTPClient@^3.2.0
   # Substituição da BLE (Não use ESP32_BLE_Arduino se for usar NimBLE)
   h2zero/NimBLE-Arduino @ 1.4.1

; Força o PlatformIO a ignorar a biblioteca BLE padrão para evitar conflitos
lib_ignore = 
    ESP32 BLE Arduino
    BLE    