; PlatformIO Project Configuration File
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
; 
; Visit documentation for the other options and examples - https://docs.platformio.org/page/projectconf.html
;
; Bibliotecas adotadas
;    As duas primeiras (makuna/Task e crankyoldgit/IRremoteESP8266) estão em lib, pois a 
;    versao presente no platformio é incompatível com o projeto
;        Gerencia a execução multitarefa cooperativa, permite agendar funções sem travar o processador com delay()
;              makuna/Task @ 1.1.6 
;        Enviar e receber sinais de infravermelho, suporta centenas de protocolos de controles remotos (ar-condicionado, TVs, etc.).
;              crankyoldgit/IRremoteESP8266@^2.7.11 -> Infelizmente, versao presente no platformio é incompatível com o projeto
;
;    As demais são as do proprio repositorio do platformio 
;        Fornece camada de abstração comum para que diferentes sensores físicos entreguem dados em formato padronizado.
;              adafruit/Adafruit Unified Sensor @^1.1.4
;        Leitura de temperatura e umidade dos sensores DHT11, DHT21 e DHT22.
;              adafruit/DHT sensor library@^1.4.3
;        Monitoramento de energia elétrica, calculando corrente (RMS), tensão e potência real via sensores não invasivos.
;              openenergymonitor/EmonLib @ 1.1.0
;        Serializar e desserializar JSON. Comunicação entre o microcontrolador e APIs ou bancos de dados.
;              bblanchon/ArduinoJson @ 6.19.4
;        Implementa MQTT. Permite publicação e assinatura de mensagens em tópicos de um Broker.
;              knolleary/PubSubClient @ 2.8.0
;        Conecta-se a servidores de tempo na rede para sincronizar o relógio interno do microcontrolador com a hora oficial (UTC).
;              arduino-libraries/NTPClient@^3.2.0
;        Versão otimizada da stack Bluetooth BLE para ESP32. Menor uso de memória RAM e processamento.
;              h2zero/NimBLE-Arduino @ 1.4.1
;        Define pacote para compilar código para ESP32. A versão 3.5.0. é referente a outubro de 2021.
;              platform = espressif32@3.5.0

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DDEVICE_TYPE=TYPE_CONTROLLER
monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
lib_deps =
   adafruit/Adafruit Unified Sensor @^1.1.4
   adafruit/DHT sensor library@^1.4.3
   openenergymonitor/EmonLib @ 1.1.0
   bblanchon/ArduinoJson @ 6.19.4
   knolleary/PubSubClient @ 2.8.0
   arduino-libraries/NTPClient@^3.2.0
   h2zero/NimBLE-Arduino @ 1.4.1

lib_extra_dirs = ../common_lib

; Ignora as bibliotecas padrões do BLE.
lib_ignore = 
    ESP32 BLE Arduino
    BLE     